### ISSUE TITLE
Enable REGEXP_* functions 

### ISSUE THREAD

**Issue by ThomasBestfleisch** [exasol/tableau-connector#14]
Enable REGEXP_* functions in Tableau  https://help.tableau.com/current/pro/desktop/en-us/functions_functions_additional.htm

**Comment by AnastasiiaSergienko** [comment]
Example from postgres dialect: https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_odbc/dialect.tdd
