### ISSUE TITLE
Tableau Kerberos Support

### ISSUE THREAD

**Issue by ThomasBestfleisch** [exasol/tableau-connector#15]
Add Kerberos Support to Tableau :

- Tableau Desktop , e.g. on Windows no user/password is needed
- Single Sign On for Tableau Server -> Kerberos Delegation

**Comment by redcatbear** [comment]
Please investigate if desktop client and server use the same mechanism in the connector. If not, please split into two separate tickets.

**Comment by chiaradiamarcelo** [comment]
It looks like, at lest for JDBC and Tableau Desktop this might be possible, as there's a sample implementation of a PostgreSQL connector that uses it, at https://github.com/tableau/connector-plugin-sdk/tree/3c5aef7735c0539906db49ed1c627224b4bd5cdc/samples/scenarios/jdbc_kerberos

Will further investigate if can be done also for ODBJ/Tableau Server
