### ISSUE TITLE
REGEX functions not visible in Tableau

### ISSUE THREAD

**Issue by ugamarkj** [exasol/tableau-connector#30]
I've connected to Exasol using the .trex connector and I'm not seeing the REGEX functions available in the Tableau calculations Window. Let me know what I can do to help troubleshoot. Happy to jump on a WebEx.

**Comment by kaklakariada** [comment]
Thank you @ugamarkj  for your ticket. I will look into this once Kerberos support #15 is finished.

**Comment by kaklakariada** [comment]
This bug is fixed with release [0.3.0](https://github.com/exasol/tableau-connector/releases/tag/0.3.0) of the connector.
