### ISSUE TITLE
Translate `LIMIT 0` to `WHERE FALSE`

### ISSUE THREAD

**Issue by redcatbear** [exasol/tableau-connector#6]
## Situation

Up to and including Exasol 7.0.x `LIMIT 0` is not optimized to the point that no query is executed. Instead a couple of rows are fetched and the limit is applied afterwards. In other `LIMIT` scenarios this is negligible, but in case users specifically set `LIMIT 0` they use that to express that the query should not really search for data. `WHERE FALSE` is a better way to express this on EXASOL.

## Investigation

1. Find out if the tableau connector description allows replacing the `LIMIT` clause by a `WHERE` condition that always evaluates to `false`.
2. If so, investigate side effects
3. If side effects are minor, implement

**Comment by chiaradiamarcelo** [comment]
As @exatobr suggested,

"
Maybe the technical solution could be easy
Could we simply replace the yes/no entries for these two lines
<customization name="CAP_QUERY_TOP_0_METADATA" value="yes"/>
<customization name="CAP_QUERY_WHERE_FALSE_METADATA" value="no"/>
In https://github.com/exasol/tableau-connector/blob/main/src/exasol_odbc/manifest.xml
"

**Comment by chiaradiamarcelo** [comment]
According to tableau doc available at https://tableau.github.io/connector-plugin-sdk/docs/capabilities, the proposed solution seems to be the right one
