### ISSUE TITLE
Add note to use JDBC driver >= 7.1.16

### ISSUE THREAD

**Issue by kaklakariada** [exasol/tableau-connector#61]
JDBC driver 7.1.16 will use SQL Status code 28000 (SQLSTATE_INVALID_AUTH_MODE) when authentication fails.
This status code will allow Tableau to display an appropriate error message.
Once the new version is released we must add a note to the documentation to use the new driver.

**Comment by redcatbear** [comment]
[Driver 7.1.16](https://x-up.s3.amazonaws.com/7.x/7.1.16/EXASOL_JDBC-7.1.16.tar.gz) is now available. Removing `blocked` marker.
