### ISSUE TITLE
Tableau Connector Improvement for SaaS

### ISSUE THREAD

**Issue by chiaradiamarcelo** [exasol/tableau-connector#9]
In order to connect to a SaaS database, you must specify an ODBC parameter which allows you to use your access token in the password field and connect to the database. 

Currently, when connecting to Tableau, you don't have any options to add any ODBC parameters. In fact, it's not even possible to get the ODBC logs from tableau without a [very difficult workaround|https://community.exasol.com/t5/connect-with-exasol/how-to-create-odbc-logfiles-with-tableau/ta-p/1244]. 

![image](https://user-images.githubusercontent.com/6044245/106251132-e40f2d80-6214-11eb-8750-e6903bd23fa4.png)

## Improvement

At the minimum, this box needs to be expanded to include an additional free text field "Additional ODBC Parameters" (or something similar) in order to support saas. 

An even better improvement would be to implement something like Snowflake's connector and allow you to choose your authentication method (username/password or personal access token), and change the fields for these. It looks like this:

![image](https://user-images.githubusercontent.com/6044245/106251158-eec9c280-6214-11eb-84d2-658ec42ae52f.png)

**Comment by AnastasiiaSergienko** [comment]
We don't need to implement anything special for SaaS because the ODBC driver now has the compatibility mode.
